### ISSUE TITLE
Create GitHub pages that wraps README

### ISSUE THREAD

**Issue by tclarke104** [Travis-Med-AI/med-ai#12]

**Comment by j718** [comment]
I looked through a bunch of gatsby templates. Which of these is your favorite? I like the first one most @tclarke104 

- https://hasura.io/learn/graphql/react/introduction/
- https://rocketdocs.netlify.app/
- https://gatsby-serif.netlify.app/
- https://gatsby-starter-hero-blog.greglobinski.com/

**Comment by tclarke104** [comment]
First one looks great
